{{- if .Values.fraudDetection.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-detection
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: fraud-detection
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}

