apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  labels:
    app: fraud-detection
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/fraud_detection_db
      kafka:
        bootstrap-servers: kafka:9092
    server:
      port: 8081
    app:
      kafka:
        topics:
          transaction-evaluated: transaction-evaluated
          transaction-status-updated: transaction-status-updated
          customer-action-received: customer-action-received
