apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  selector:
    app: fraud-detection
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
